# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authour',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_Date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_Date',
            new_name='published_date',
        ),
    ]
